version: "3.9"

services:
  db:
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db/data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
